In [2]:
import pandas as pd
df=pd.read_csv("C:\\Users\\Ibtissam Bukhari\\Desktop\\Projects\\customer-churn-mlops\\data\\raw\\Telco-Customer-Churn.csv")

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.9 MB

In [5]:
target_column = "Churn"

X = df.drop(columns=[target_column, "customerID"])
y = df[target_column]

In [6]:
X.shape

(7043, 19)

In [7]:
y.shape

(7043,)

In [8]:
X.columns.tolist()

['gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges']

In [9]:
X["TotalCharges"] = pd.to_numeric(
    X["TotalCharges"],
    errors="coerce"
)

In [10]:
X["TotalCharges"].dtype

dtype('float64')

In [11]:
X["TotalCharges"].isna().sum()

np.int64(11)

In [12]:
X.loc[
    X["TotalCharges"].isna(),
    ["tenure", "MonthlyCharges", "TotalCharges"]
]

      tenure  MonthlyCharges  TotalCharges
488        0           52.55           NaN
753        0           20.25           NaN
936        0           80.85           NaN
1082       0           25.75           NaN
1340       0           56.05           NaN
3331       0           19.85           NaN
3826       0           25.35           NaN
4380       0           20.00           NaN
5218       0           19.70           NaN
6670       0           73.35           NaN
6754       0           61.90           NaN

In [13]:
X["TotalCharges"] = X["TotalCharges"].fillna(0)

In [14]:
X["TotalCharges"].isna().sum()

np.int64(0)

In [15]:
numeric_features = [
    "SeniorCitizen",
    "tenure",
    "MonthlyCharges",
    "TotalCharges"
]

In [16]:
categorical_features = [
    "gender",
    "Partner",
    "Dependents",
    "PhoneService",
    "MultipleLines",
    "InternetService",
    "OnlineSecurity",
    "OnlineBackup",
    "DeviceProtection",
    "TechSupport",
    "StreamingTV",
    "StreamingMovies",
    "Contract",
    "PaperlessBilling",
    "PaymentMethod"
]

In [17]:
len(numeric_features), len(categorical_features)

(4, 15)

In [18]:
set(numeric_features) & set(categorical_features)

set()

In [19]:
from sklearn.preprocessing import OneHotEncoder

In [20]:
categorical_encoder = OneHotEncoder(
    handle_unknown="ignore"
)

In [21]:
categorical_encoder.fit(X[categorical_features])

OneHotEncoder(handle_unknown='ignore')

In [22]:
categorical_encoder.categories_

[array(['Female', 'Male'], dtype=object),
 array(['No', 'Yes'], dtype=object),
 array(['No', 'Yes'], dtype=object),
 array(['No', 'Yes'], dtype=object),
 array(['No', 'No phone service', 'Yes'], dtype=object),
 array(['DSL', 'Fiber optic', 'No'], dtype=object),
 array(['No', 'No internet service', 'Yes'], dtype=object),
 array(['No', 'No internet service', 'Yes'], dtype=object),
 array(['No', 'No internet service', 'Yes'], dtype=object),
 array(['No', 'No internet service', 'Yes'], dtype=object),
 array(['No', 'No internet service', 'Yes'], dtype=object),
 array(['No', 'No internet service', 'Yes'], dtype=object),
 array(['Month-to-month', 'One year', 'Two year'], dtype=object),
 array(['No', 'Yes'], dtype=object),
 array(['Bank transfer (automatic)', 'Credit card (automatic)',
        'Electronic check', 'Mailed check'], dtype=object)]

In [23]:
encoded_categorical = categorical_encoder.transform(
    X[categorical_features]
)

In [24]:
encoded_categorical.shape

(7043, 41)

In [25]:
encoded_categorical.toarray()[:5]

array([[1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0.,
        0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0.,
        1., 0., 0., 0., 1., 0., 0., 1., 0.],
       [0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0.,
        1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0.,
        0., 1., 0., 1., 0., 0., 0., 0., 1.],
       [0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0.,
        1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0.,
        1., 0., 0., 0., 1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
        1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0.,
        0., 1., 0., 1., 0., 1., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0.,
        0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0.,
        1., 0., 0., 0., 1., 0., 0., 1., 0.]])

In [26]:
X[numeric_features].describe()

       SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    7043.000000  7043.000000     7043.000000   7043.000000
mean        0.162147    32.371149       64.761692   2279.734304
std         0.368612    24.559481       30.090047   2266.794470
min         0.000000     0.000000       18.250000      0.000000
25%         0.000000     9.000000       35.500000    398.550000
50%         0.000000    29.000000       70.350000   1394.550000
75%         0.000000    55.000000       89.850000   3786.600000
max         1.000000    72.000000      118.750000   8684.800000

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.30,
    stratify=y,
    random_state=42
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    stratify=y_temp,
    random_state=42
)

In [28]:
X_train.shape, X_val.shape, X_test.shape

((4930, 19), (1056, 19), (1057, 19))

In [29]:
y_train.value_counts(normalize=True)
y_val.value_counts(normalize=True)
y_test.value_counts(normalize=True)

Churn
No     0.734153
Yes    0.265847
Name: proportion, dtype: float64

In [30]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

preprocessor = ColumnTransformer(
    transformers=[
        ("numeric", StandardScaler(), numeric_features),
        (
            "categorical",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        )
    ]
)

In [31]:
X_train_processed = preprocessor.fit_transform(X_train)

X_val_processed = preprocessor.transform(X_val)

X_test_processed = preprocessor.transform(X_test)

In [32]:
X_train_processed.shape, X_val_processed.shape, X_test_processed.shape

((4930, 45), (1056, 45), (1057, 45))

In [33]:
y_train = y_train.map({"No": 0, "Yes": 1})
y_val = y_val.map({"No": 0, "Yes": 1})
y_test = y_test.map({"No": 0, "Yes": 1})

In [34]:
y_train.value_counts()

Churn
0    3622
1    1308
Name: count, dtype: int64

In [35]:
y_val.value_counts()

Churn
0    776
1    280
Name: count, dtype: int64

In [36]:
y_test.value_counts()

Churn
0    776
1    281
Name: count, dtype: int64

In [37]:
from sklearn.linear_model import LogisticRegression

In [38]:
logistic_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

In [39]:
logistic_model.fit(
    X_train_processed,
    y_train
)

LogisticRegression(max_iter=1000, random_state=42)

In [40]:
y_val_pred = logistic_model.predict(X_val_processed)

In [41]:
y_val_pred[:5]

array([0, 1, 0, 0, 1])

In [42]:
y_val_proba = logistic_model.predict_proba(X_val_processed)[:, 1]

In [43]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

print("Accuracy :", accuracy_score(y_val, y_val_pred))
print("Precision:", precision_score(y_val, y_val_pred))
print("Recall   :", recall_score(y_val, y_val_pred))
print("F1 Score :", f1_score(y_val, y_val_pred))
print("ROC-AUC  :", roc_auc_score(y_val, y_val_proba))

Accuracy : 0.8058712121212122
Precision: 0.6459143968871596
Recall   : 0.5928571428571429
F1 Score : 0.6182495344506518
ROC-AUC  : 0.8454321612665685

In [44]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_val, y_val_pred)

array([[685,  91],
       [114, 166]])

In [45]:
# Test Several Threshold
from sklearn.metrics import precision_score, recall_score, f1_score

thresholds = [0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50]

threshold_results = []

for threshold in thresholds:
    y_val_threshold = (y_val_proba >= threshold).astype(int)

    precision = precision_score(y_val, y_val_threshold)
    recall = recall_score(y_val, y_val_threshold)
    f1 = f1_score(y_val, y_val_threshold)

    threshold_results.append({
        "threshold": threshold,
        "precision": precision,
        "recall": recall,
        "f1": f1
    })

In [46]:
threshold_results_df = pd.DataFrame(threshold_results)

threshold_results_df

   threshold  precision    recall        f1
0       0.20   0.472062  0.875000  0.613267
1       0.25   0.495763  0.835714  0.622340
2       0.30   0.518779  0.789286  0.626062
3       0.35   0.533163  0.746429  0.622024
4       0.40   0.557746  0.707143  0.623622
5       0.45   0.601974  0.653571  0.626712
6       0.50   0.645914  0.592857  0.618250

In [47]:
logistic_balanced = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    random_state=42
)

In [48]:
logistic_balanced.fit(
    X_train_processed,
    y_train
)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

In [49]:
y_val_pred_balanced = logistic_balanced.predict(X_val_processed)

y_val_proba_balanced = logistic_balanced.predict_proba(
    X_val_processed
)[:, 1]

In [50]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

print("Accuracy :", accuracy_score(y_val, y_val_pred_balanced))
print("Precision:", precision_score(y_val, y_val_pred_balanced))
print("Recall   :", recall_score(y_val, y_val_pred_balanced))
print("F1 Score :", f1_score(y_val, y_val_pred_balanced))
print("ROC-AUC  :", roc_auc_score(y_val, y_val_proba_balanced))

Accuracy : 0.7395833333333334
Precision: 0.5055432372505543
Recall   : 0.8142857142857143
F1 Score : 0.6238030095759234
ROC-AUC  : 0.8448798784977909

In [51]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_val, y_val_pred_balanced)

array([[553, 223],
       [ 52, 228]])

In [52]:
y_val_proba_balanced

array([0.05391829, 0.7918151 , 0.18805981, ..., 0.850397  , 0.13127846,
       0.42733248], shape=(1056,))

In [53]:
balanced_threshold_results = []

for threshold in thresholds:
    y_val_threshold = (
        y_val_proba_balanced >= threshold
    ).astype(int)

    precision = precision_score(
        y_val,
        y_val_threshold
    )

    recall = recall_score(
        y_val,
        y_val_threshold
    )

    f1 = f1_score(
        y_val,
        y_val_threshold
    )

    balanced_threshold_results.append({
        "threshold": threshold,
        "precision": precision,
        "recall": recall,
        "f1": f1
    })

In [54]:
balanced_threshold_df = pd.DataFrame(
    balanced_threshold_results
)

balanced_threshold_df

   threshold  precision    recall        f1
0       0.20   0.385387  0.960714  0.550102
1       0.25   0.401216  0.942857  0.562900
2       0.30   0.424390  0.932143  0.583240
3       0.35   0.444637  0.917857  0.599068
4       0.40   0.467925  0.885714  0.612346
5       0.45   0.483806  0.853571  0.617571
6       0.50   0.505543  0.814286  0.623803

In [55]:
import xgboost

print(xgboost.__version__)

3.2.0

In [56]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=4,
    random_state=42,
    eval_metric="logloss"
)

In [57]:
xgb_model.fit(
    X_train_processed,
    y_train
)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [58]:
y_val_pred_xgb = xgb_model.predict(X_val_processed)

y_val_proba_xgb = xgb_model.predict_proba(
    X_val_processed
)[:, 1]

In [59]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

xgb_accuracy = accuracy_score(
    y_val,
    y_val_pred_xgb
)

xgb_precision = precision_score(
    y_val,
    y_val_pred_xgb
)

xgb_recall = recall_score(
    y_val,
    y_val_pred_xgb
)

xgb_f1 = f1_score(
    y_val,
    y_val_pred_xgb
)

xgb_roc_auc = roc_auc_score(
    y_val,
    y_val_proba_xgb
)

print("XGBoost Validation Metrics")
print("---------------------------")
print(f"Accuracy : {xgb_accuracy:.4f}")
print(f"Precision: {xgb_precision:.4f}")
print(f"Recall   : {xgb_recall:.4f}")
print(f"F1 Score : {xgb_f1:.4f}")
print(f"ROC-AUC  : {xgb_roc_auc:.4f}")

XGBoost Validation Metrics
---------------------------
Accuracy : 0.7992
Precision: 0.6441
Recall   : 0.5429
F1 Score : 0.5891
ROC-AUC  : 0.8468

In [60]:
xgb_threshold_results = []

for threshold in thresholds:
    y_val_threshold = (
        y_val_proba_xgb >= threshold
    ).astype(int)

    precision = precision_score(
        y_val,
        y_val_threshold
    )

    recall = recall_score(
        y_val,
        y_val_threshold
    )

    f1 = f1_score(
        y_val,
        y_val_threshold
    )

    xgb_threshold_results.append({
        "threshold": threshold,
        "precision": precision,
        "recall": recall,
        "f1": f1
    })

In [61]:
xgb_threshold_df = pd.DataFrame(
    xgb_threshold_results
)

xgb_threshold_df

   threshold  precision    recall        f1
0       0.20   0.482490  0.885714  0.624685
1       0.25   0.508696  0.835714  0.632432
2       0.30   0.532530  0.789286  0.635971
3       0.35   0.553672  0.700000  0.618297
4       0.40   0.575949  0.650000  0.610738
5       0.45   0.611940  0.585714  0.598540
6       0.50   0.644068  0.542857  0.589147

In [62]:
print("XGBoost best threshold:")
print(
    xgb_threshold_df.loc[
        xgb_threshold_df["f1"].idxmax()
    ]
)

XGBoost best threshold:
threshold    0.300000
precision    0.532530
recall       0.789286
f1           0.635971
Name: 2, dtype: float64

In [63]:
print("Balanced Logistic Regression best threshold:")
print(
    balanced_threshold_df.loc[
        balanced_threshold_df["f1"].idxmax()
    ]
)

Balanced Logistic Regression best threshold:
threshold    0.500000
precision    0.505543
recall       0.814286
f1           0.623803
Name: 6, dtype: float64

In [64]:
# Hyperparameter Tunning
xgb_model = XGBClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=4,
    random_state=42,
    eval_metric="logloss"
)

In [65]:
from sklearn.model_selection import RandomizedSearchCV
from xgboost import XGBClassifier
xgb_tuning_model = XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42
)
param_distributions = {
    "n_estimators": [100, 200, 300, 400],
    "learning_rate": [0.03, 0.05, 0.1],
    "max_depth": [3, 4, 5],
    "subsample": [0.8, 1.0],
    "colsample_bytree": [0.8, 1.0]
}
xgb_random_search = RandomizedSearchCV(
    estimator=xgb_tuning_model,
    param_distributions=param_distributions,
    n_iter=15,
    scoring="f1",
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=1
)

In [66]:
xgb_random_search.fit(
    X_train_processed,
    y_train
)

Fitting 5 folds for each of 15 candidates, totalling 75 fits

RandomizedSearchCV(cv=5,
                   estimator=XGBClassifier(base_score=None, booster=None,
                                           callbacks=None,
                                           colsample_bylevel=None,
                                           colsample_bynode=None,
                                           colsample_bytree=None, device=None,
                                           early_stopping_rounds=None,
                                           enable_categorical=False,
                                           eval_metric='logloss',
                                           feature_types=None,
                                           feature_weights=None, gamma=None,
                                           grow_policy=None,
                                           importance_type=None,
                                           interaction_cons...
                                           min_child_weight=None, missing=nan,
                                           monotone_constraints=None,
                                           multi_strategy=None,
                                           n_estimators=None, n_jobs=None,
                                           num_parallel_tree=None, ...),
                   n_iter=15, n_jobs=-1,
                   param_distributions={'colsample_bytree': [0.8, 1.0],
                                        'learning_rate': [0.03, 0.05, 0.1],
                                        'max_depth': [3, 4, 5],
                                        'n_estimators': [100, 200, 300, 400],
                                        'subsample': [0.8, 1.0]},
                   random_state=42, scoring='f1', verbose=1)

In [67]:
print("Best parameters:")
print(xgb_random_search.best_params_)

Best parameters:
{'subsample': 1.0, 'n_estimators': 200, 'max_depth': 5, 'learning_rate': 0.03, 'colsample_bytree': 0.8}

In [68]:
print("Best cross-validation F1:")
print(xgb_random_search.best_score_)

Best cross-validation F1:
0.590478524540454

In [69]:
best_xgb_model = xgb_random_search.best_estimator_

In [70]:
best_xgb_model = xgb_random_search.best_estimator_

In [71]:
y_val_pred_tuned_xgb = best_xgb_model.predict(
    X_val_processed
)

y_val_proba_tuned_xgb = best_xgb_model.predict_proba(
    X_val_processed
)[:, 1]

In [72]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

print("Tuned XGBoost Validation Metrics")
print("--------------------------------")

print(
    f"Accuracy : "
    f"{accuracy_score(y_val, y_val_pred_tuned_xgb):.4f}"
)

print(
    f"Precision: "
    f"{precision_score(y_val, y_val_pred_tuned_xgb):.4f}"
)

print(
    f"Recall   : "
    f"{recall_score(y_val, y_val_pred_tuned_xgb):.4f}"
)

print(
    f"F1 Score : "
    f"{f1_score(y_val, y_val_pred_tuned_xgb):.4f}"
)

print(
    f"ROC-AUC  : "
    f"{roc_auc_score(y_val, y_val_proba_tuned_xgb):.4f}"
)

Tuned XGBoost Validation Metrics
--------------------------------
Accuracy : 0.8002
Precision: 0.6432
Recall   : 0.5536
F1 Score : 0.5950
ROC-AUC  : 0.8460

In [73]:
tuned_xgb_threshold_results = []

for threshold in thresholds:
    y_val_threshold = (
        y_val_proba_tuned_xgb >= threshold
    ).astype(int)

    precision = precision_score(
        y_val,
        y_val_threshold
    )

    recall = recall_score(
        y_val,
        y_val_threshold
    )

    f1 = f1_score(
        y_val,
        y_val_threshold
    )

    tuned_xgb_threshold_results.append({
        "threshold": threshold,
        "precision": precision,
        "recall": recall,
        "f1": f1
    })

In [74]:
tuned_xgb_threshold_df = pd.DataFrame(
    tuned_xgb_threshold_results
)

tuned_xgb_threshold_df

   threshold  precision    recall        f1
0       0.20   0.474903  0.878571  0.616541
1       0.25   0.505308  0.850000  0.633822
2       0.30   0.529691  0.796429  0.636234
3       0.35   0.565460  0.725000  0.635368
4       0.40   0.581761  0.660714  0.618729
5       0.45   0.608696  0.600000  0.604317
6       0.50   0.643154  0.553571  0.595010

In [75]:
xgb_model.fit(
    X_train_processed,
    y_train
)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [76]:
y_test_proba_xgb = xgb_model.predict_proba(
    X_test_processed
)[:, 1]

In [77]:
final_threshold = 0.30

y_test_pred_xgb = (
    y_test_proba_xgb >= final_threshold
).astype(int)

In [78]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)

test_accuracy = accuracy_score(
    y_test,
    y_test_pred_xgb
)

test_precision = precision_score(
    y_test,
    y_test_pred_xgb
)

test_recall = recall_score(
    y_test,
    y_test_pred_xgb
)

test_f1 = f1_score(
    y_test,
    y_test_pred_xgb
)

test_roc_auc = roc_auc_score(
    y_test,
    y_test_proba_xgb
)

print("Final XGBoost Test Metrics")
print("--------------------------")
print(f"Accuracy : {test_accuracy:.4f}")
print(f"Precision: {test_precision:.4f}")
print(f"Recall   : {test_recall:.4f}")
print(f"F1 Score : {test_f1:.4f}")
print(f"ROC-AUC  : {test_roc_auc:.4f}")

Final XGBoost Test Metrics
--------------------------
Accuracy : 0.7692
Precision: 0.5501
Recall   : 0.7224
F1 Score : 0.6246
ROC-AUC  : 0.8313

In [79]:
cm = confusion_matrix(
    y_test,
    y_test_pred_xgb
)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[610 166]
 [ 78 203]]

# Final Model Evaluation

After comparing Logistic Regression, balanced Logistic Regression, and XGBoost, XGBoost was selected as the final model for this project.

The selected configuration was:

- **Model:** XGBoost
- **Decision threshold:** 0.30
- **Validation ROC-AUC:** 0.8468
- **Validation F1:** 0.6360
- **Validation Recall:** 0.7893
- **Validation Precision:** 0.5325

The selected threshold of 0.30 was chosen based on validation-set performance. A lower threshold was preferred because identifying potential churners is important for the business, even though this increases the number of false positives.

## Final Test Evaluation

The test set was kept completely untouched during model selection, hyperparameter tuning, and threshold selection. It was used only for the final evaluation.

Final test performance:

- **Accuracy:** 0.7692
- **Precision:** 0.5501
- **Recall:** 0.7224
- **F1 Score:** 0.6246
- **ROC-AUC:** 0.8313

### Confusion Matrix

```text
[[610 166]
 [ 78 203]]

In [80]:
# Testing the modular codes

In [81]:
print("Numeric features:")
print(numeric_features)

print("\nCategorical features:")
print(categorical_features)

print("\nTotal input features:")
print(len(numeric_features) + len(categorical_features))

Numeric features:
['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']

Categorical features:
['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']

Total input features:
19

In [82]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

In [83]:
from src.features.preprocessing import clean_total_charges

In [84]:
test_df = pd.DataFrame({
    "TotalCharges": ["29.85", "1889.5", ""]
})

cleaned_test_df = clean_total_charges(test_df)

print(cleaned_test_df)
print(cleaned_test_df.dtypes)

   TotalCharges
0         29.85
1       1889.50
2          0.00
TotalCharges    float64
dtype: object

In [85]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

In [86]:
import pandas as pd

In [87]:
from src.features.preprocessing import prepare_features
test_df = pd.DataFrame({
    "customerID": ["001", "002"],
    "TotalCharges": ["29.85", ""],
    "Churn": ["No", "Yes"],
})

prepared_df = prepare_features(test_df)

print(prepared_df)
print("\nColumns:")
print(prepared_df.columns.tolist())

   TotalCharges
0         29.85
1          0.00

Columns:
['TotalCharges']

In [88]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))
from src.features.preprocessing import create_preprocessor,TARGET_COLUMN

In [89]:
preprocessor_test = create_preprocessor()

print(preprocessor_test)

ColumnTransformer(transformers=[('numeric', StandardScaler(),
                                 ['SeniorCitizen', 'tenure', 'MonthlyCharges',
                                  'TotalCharges']),
                                ('categorical',
                                 OneHotEncoder(handle_unknown='ignore'),
                                 ['gender', 'Partner', 'Dependents',
                                  'PhoneService', 'MultipleLines',
                                  'InternetService', 'OnlineSecurity',
                                  'OnlineBackup', 'DeviceProtection',
                                  'TechSupport', 'StreamingTV',
                                  'StreamingMovies', 'Contract',
                                  'PaperlessBilling', 'PaymentMethod'])])

In [90]:
prepared_full = prepare_features(df)

print("Shape:", prepared_full.shape)
print("Columns:", prepared_full.columns.tolist())

Shape: (7043, 19)
Columns: ['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges']

In [91]:
preprocessor_test.fit(prepared_full)

ColumnTransformer(transformers=[('numeric', StandardScaler(),
                                 ['SeniorCitizen', 'tenure', 'MonthlyCharges',
                                  'TotalCharges']),
                                ('categorical',
                                 OneHotEncoder(handle_unknown='ignore'),
                                 ['gender', 'Partner', 'Dependents',
                                  'PhoneService', 'MultipleLines',
                                  'InternetService', 'OnlineSecurity',
                                  'OnlineBackup', 'DeviceProtection',
                                  'TechSupport', 'StreamingTV',
                                  'StreamingMovies', 'Contract',
                                  'PaperlessBilling', 'PaymentMethod'])])

In [92]:
processed_test = preprocessor_test.transform(prepared_full)

print("Processed shape:", processed_test.shape)

Processed shape: (7043, 45)

In [93]:
X = prepare_features(df)
y = df[TARGET_COLUMN].map({"No": 0, "Yes": 1})

In [94]:
from sklearn.model_selection import train_test_split

X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.30,
    stratify=y,
    random_state=42
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    stratify=y_temp,
    random_state=42
)

In [95]:
print("Train:", X_train.shape, y_train.shape)
print("Validation:", X_val.shape, y_val.shape)
print("Test:", X_test.shape, y_test.shape)

Train: (4930, 19) (4930,)
Validation: (1056, 19) (1056,)
Test: (1057, 19) (1057,)

In [96]:
preprocessor = create_preprocessor()

In [97]:
preprocessor.fit(X_train)

ColumnTransformer(transformers=[('numeric', StandardScaler(),
                                 ['SeniorCitizen', 'tenure', 'MonthlyCharges',
                                  'TotalCharges']),
                                ('categorical',
                                 OneHotEncoder(handle_unknown='ignore'),
                                 ['gender', 'Partner', 'Dependents',
                                  'PhoneService', 'MultipleLines',
                                  'InternetService', 'OnlineSecurity',
                                  'OnlineBackup', 'DeviceProtection',
                                  'TechSupport', 'StreamingTV',
                                  'StreamingMovies', 'Contract',
                                  'PaperlessBilling', 'PaymentMethod'])])

In [98]:
X_train_processed = preprocessor.transform(X_train)

X_val_processed = preprocessor.transform(X_val)

X_test_processed = preprocessor.transform(X_test)

In [99]:
print("Train:", X_train_processed.shape)
print("Validation:", X_val_processed.shape)
print("Test:", X_test_processed.shape)

Train: (4930, 45)
Validation: (1056, 45)
Test: (1057, 45)

In [100]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

from src.data.splitting import split_data

In [101]:
X_train, X_val, X_test, y_train, y_val, y_test = split_data(
    X,
    y,
)

In [102]:
print("X_train:", X_train.shape)
print("X_val:", X_val.shape)
print("X_test:", X_test.shape)

print("y_train:", y_train.shape)
print("y_val:", y_val.shape)
print("y_test:", y_test.shape)

X_train: (4930, 19)
X_val: (1056, 19)
X_test: (1057, 19)
y_train: (4930,)
y_val: (1056,)
y_test: (1057,)

In [103]:
print("Original:")
print(y.value_counts(normalize=True))

print("\nTraining:")
print(y_train.value_counts(normalize=True))

print("\nValidation:")
print(y_val.value_counts(normalize=True))

print("\nTest:")
print(y_test.value_counts(normalize=True))

Original:
Churn
0    0.73463
1    0.26537
Name: proportion, dtype: float64

Training:
Churn
0    0.734686
1    0.265314
Name: proportion, dtype: float64

Validation:
Churn
0    0.734848
1    0.265152
Name: proportion, dtype: float64

Test:
Churn
0    0.734153
1    0.265847
Name: proportion, dtype: float64

In [104]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))
from src.features.preprocessing import prepare_target

In [105]:
y_prepared = prepare_target(y)

print(y_prepared.head())
print(y_prepared.dtype)
print(y_prepared.value_counts())

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: Churn, dtype: float64
float64
Series([], Name: count, dtype: int64)

In [106]:
print(y.head())
print(y.dtype)
print(y.unique())

0    0
1    0
2    1
3    0
4    1
Name: Churn, dtype: int64
int64
[0 1]

In [107]:
y_raw = df["Churn"]

y_prepared = prepare_target(y_raw)

print(y_prepared.head())
print(y_prepared.dtype)
print(y_prepared.value_counts())

0    0
1    0
2    1
3    0
4    1
Name: Churn, dtype: int64
int64
Churn
0    5174
1    1869
Name: count, dtype: int64

In [108]:
X_prepared = prepare_features(df)

print("Shape:", X_prepared.shape)
print("\nColumns:")
print(X_prepared.columns.tolist())

Shape: (7043, 19)

Columns:
['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges']

In [109]:
print("customerID present:", "customerID" in X_prepared.columns)
print("Churn present:", "Churn" in X_prepared.columns)

customerID present: False
Churn present: False

In [110]:
print(X_prepared["TotalCharges"].dtype)
print("Missing TotalCharges:", X_prepared["TotalCharges"].isna().sum())

float64
Missing TotalCharges: 0

In [111]:
# Overall testing

In [112]:
from src.features.preprocessing import (
    prepare_features,
    prepare_target,
    create_preprocessor,
)

from src.data.splitting import split_data

In [113]:
X = prepare_features(df)
y = prepare_target(df["Churn"])

In [114]:
X_train, X_val, X_test, y_train, y_val, y_test = split_data(
    X,
    y,
)

In [115]:
preprocessor = create_preprocessor()

In [116]:
preprocessor

ColumnTransformer(transformers=[('numeric', StandardScaler(),
                                 ['SeniorCitizen', 'tenure', 'MonthlyCharges',
                                  'TotalCharges']),
                                ('categorical',
                                 OneHotEncoder(handle_unknown='ignore'),
                                 ['gender', 'Partner', 'Dependents',
                                  'PhoneService', 'MultipleLines',
                                  'InternetService', 'OnlineSecurity',
                                  'OnlineBackup', 'DeviceProtection',
                                  'TechSupport', 'StreamingTV',
                                  'StreamingMovies', 'Contract',
                                  'PaperlessBilling', 'PaymentMethod'])])

In [117]:
preprocessor.fit(X_train)

ColumnTransformer(transformers=[('numeric', StandardScaler(),
                                 ['SeniorCitizen', 'tenure', 'MonthlyCharges',
                                  'TotalCharges']),
                                ('categorical',
                                 OneHotEncoder(handle_unknown='ignore'),
                                 ['gender', 'Partner', 'Dependents',
                                  'PhoneService', 'MultipleLines',
                                  'InternetService', 'OnlineSecurity',
                                  'OnlineBackup', 'DeviceProtection',
                                  'TechSupport', 'StreamingTV',
                                  'StreamingMovies', 'Contract',
                                  'PaperlessBilling', 'PaymentMethod'])])

In [118]:
X_train_processed = preprocessor.transform(X_train)

X_val_processed = preprocessor.transform(X_val)

X_test_processed = preprocessor.transform(X_test)

In [119]:
print("X_train_processed:", X_train_processed.shape)
print("X_val_processed:", X_val_processed.shape)
print("X_test_processed:", X_test_processed.shape)

X_train_processed: (4930, 45)
X_val_processed: (1056, 45)
X_test_processed: (1057, 45)

In [120]:
print(type(X_train_processed))

<class 'numpy.ndarray'>

In [121]:
from src.models.train import train_model

In [122]:
model = train_model(
    X_train_processed,
    y_train.to_numpy(),
)

In [123]:
print(type(model))
print(model.n_estimators)
print(model.max_depth)
print(model.learning_rate)

<class 'xgboost.sklearn.XGBClassifier'>
200
4
0.05

In [124]:
from src.models.evaluate import (
    predict_probabilities,
    apply_threshold,
    calculate_metrics,
)

In [125]:
y_val_proba = predict_probabilities(
    model,
    X_val_processed,
)

In [126]:
print(y_val_proba[:5])
print(y_val_proba.shape)

[0.00465464 0.43449008 0.05063653 0.00729532 0.8572801 ]
(1056,)

In [127]:
y_val_pred = apply_threshold(
    y_val_proba,
    0.30,
)

In [128]:
validation_metrics = calculate_metrics(
    y_val.to_numpy(),
    y_val_pred,
    y_val_proba,
)

print(validation_metrics)

{'precision': 0.5325301204819277, 'recall': 0.7892857142857143, 'f1': 0.6359712230215827, 'roc_auc': 0.8468059646539028}

In [129]:
from src.models.evaluate import evaluate_thresholds

In [130]:
thresholds = [
    0.20,
    0.25,
    0.30,
    0.35,
    0.40,
    0.45,
    0.50,
]

In [131]:
threshold_results = evaluate_thresholds(
    y_val.to_numpy(),
    y_val_proba,
    thresholds,
)

In [132]:
threshold_df = pd.DataFrame(
    threshold_results
)

threshold_df

   precision    recall        f1   roc_auc  threshold
0   0.482490  0.885714  0.624685  0.846806       0.20
1   0.508696  0.835714  0.632432  0.846806       0.25
2   0.532530  0.789286  0.635971  0.846806       0.30
3   0.553672  0.700000  0.618297  0.846806       0.35
4   0.575949  0.650000  0.610738  0.846806       0.40
5   0.611940  0.585714  0.598540  0.846806       0.45
6   0.644068  0.542857  0.589147  0.846806       0.50

In [133]:
threshold_results = evaluate_thresholds(
    y_val.to_numpy(),
    y_val_proba,
    thresholds,
)

threshold_df = pd.DataFrame(threshold_results)

threshold_df

   precision    recall        f1   roc_auc  threshold
0   0.482490  0.885714  0.624685  0.846806       0.20
1   0.508696  0.835714  0.632432  0.846806       0.25
2   0.532530  0.789286  0.635971  0.846806       0.30
3   0.553672  0.700000  0.618297  0.846806       0.35
4   0.575949  0.650000  0.610738  0.846806       0.40
5   0.611940  0.585714  0.598540  0.846806       0.45
6   0.644068  0.542857  0.589147  0.846806       0.50

In [134]:
best_threshold_row = threshold_df.loc[
    threshold_df["f1"].idxmax()
]

best_threshold_row

precision    0.532530
recall       0.789286
f1           0.635971
roc_auc      0.846806
threshold    0.300000
Name: 2, dtype: float64

In [135]:
# Testng Artifacts
from src.models.artifacts import ModelArtifacts
artifact = ModelArtifacts(
    model=model,
    preprocessor=preprocessor,
    threshold=0.30,
    metadata={
    "model_type": "XGBoost",
    "model_version": "1.0",
    },  
)

In [136]:
print(type(artifact))
print(artifact.threshold)
print(artifact.metadata)

<class 'src.models.artifacts.ModelArtifacts'>
0.3
{'model_type': 'XGBoost', 'model_version': '1.0'}

In [137]:
from pathlib import Path

from src.models.artifacts import (
    save_artifacts,
    load_artifacts,
)

In [138]:
artifact_path = Path(
    "../models/churn_model.joblib"
)

In [139]:
save_artifacts(
    artifact,
    artifact_path,
)

In [140]:
print(artifact_path.exists())
print(artifact_path)

True
..\models\churn_model.joblib

In [141]:
loaded_artifact = load_artifacts(
    artifact_path,
)

In [142]:
print(type(loaded_artifact))
print(loaded_artifact.threshold)
print(loaded_artifact.metadata)

<class 'src.models.artifacts.ModelArtifacts'>
0.3
{'model_type': 'XGBoost', 'model_version': '1.0'}

In [143]:
loaded_probabilities = loaded_artifact.model.predict_proba(
    X_val_processed
)[:, 1]

print(loaded_probabilities[:5])

[0.00465464 0.43449008 0.05063653 0.00729532 0.8572801 ]

In [144]:
print("Threshold:", loaded_artifact.threshold)

print(
    "Preprocessor type:",
    type(loaded_artifact.preprocessor)
)

print(
    "Model type:",
    type(loaded_artifact.model)
)

print(
    "Metadata:",
    loaded_artifact.metadata
)

Threshold: 0.3
Preprocessor type: <class 'sklearn.compose._column_transformer.ColumnTransformer'>
Model type: <class 'xgboost.sklearn.XGBClassifier'>
Metadata: {'model_type': 'XGBoost', 'model_version': '1.0'}

In [145]:
from src.models.predict import predict_customer
customer=df.iloc[[0]].copy()
results=predict_customer(customer_data=customer,artifact=loaded_artifact)
print(results)

{'churn_probability': 0.6854717135429382, 'prediction': 1}

In [146]:
results=predict_customer(df.iloc[[1]],artifact=loaded_artifact)
print(results)

{'churn_probability': 0.03169839829206467, 'prediction': 0}

In [147]:
from pathlib import Path

artifact_path = Path("../models/churn_model.joblib")

print("Artifact exists:", artifact_path.exists())
print("Artifact path:", artifact_path)

Artifact exists: True
Artifact path: ..\models\churn_model.joblib

In [148]:
from src.training_pipeline import run_training_pipeline

results = run_training_pipeline()

results

{'artifact_path': WindowsPath('C:/Users/Ibtissam Bukhari/Desktop/Projects/customer-churn-mlops/models/churn_model.joblib'),
 'validation_metrics': {'precision': 0.5325301204819277,
  'recall': 0.7892857142857143,
  'f1': 0.6359712230215827,
  'roc_auc': 0.8468059646539028},
 'test_metrics': {'precision': 0.5501355013550135,
  'recall': 0.7224199288256228,
  'f1': 0.6246153846153846,
  'roc_auc': 0.8312933374912865}}

In [149]:
from pathlib import Path

print(Path.cwd())

c:\Users\Ibtissam Bukhari\Desktop\Projects\customer-churn-mlops\notebooks

In [150]:
from src.data.ingestion import RAW_DATA_PATH

print("Raw data path:")
print(RAW_DATA_PATH)

print("\nFile exists:", RAW_DATA_PATH.exists())

Raw data path:
C:\Users\Ibtissam Bukhari\Desktop\Projects\customer-churn-mlops\data\raw\Telco-Customer-Churn.csv

File exists: True

In [151]:
import importlib
import src.data.ingestion

importlib.reload(src.data.ingestion)

print(src.data.ingestion.RAW_DATA_PATH)
print("File exists:", src.data.ingestion.RAW_DATA_PATH.exists())

C:\Users\Ibtissam Bukhari\Desktop\Projects\customer-churn-mlops\data\raw\Telco-Customer-Churn.csv
File exists: True

In [152]:
# from src.training_pipeline import run_training_pipeline

# results = run_training_pipeline()

# results

In [153]:
import importlib
import src.training_pipeline

importlib.reload(src.training_pipeline)

run_training_pipeline = src.training_pipeline.run_training_pipeline

print("Training pipeline reloaded successfully.")

Training pipeline reloaded successfully.

In [154]:
results = run_training_pipeline()

results

{'artifact_path': WindowsPath('C:/Users/Ibtissam Bukhari/Desktop/Projects/customer-churn-mlops/models/churn_model.joblib'),
 'validation_metrics': {'precision': 0.5325301204819277,
  'recall': 0.7892857142857143,
  'f1': 0.6359712230215827,
  'roc_auc': 0.8468059646539028},
 'test_metrics': {'precision': 0.5501355013550135,
  'recall': 0.7224199288256228,
  'f1': 0.6246153846153846,
  'roc_auc': 0.8312933374912865}}

In [155]:
from src.models.artifacts import load_artifacts

loaded_artifact = load_artifacts(
    results["artifact_path"]
)

print("Artifact loaded successfully.")
print("Model:", type(loaded_artifact.model))
print("Preprocessor:", type(loaded_artifact.preprocessor))
print("Threshold:", loaded_artifact.threshold)
print("Metadata:", loaded_artifact.metadata)

Artifact loaded successfully.
Model: <class 'xgboost.sklearn.XGBClassifier'>
Preprocessor: <class 'sklearn.compose._column_transformer.ColumnTransformer'>
Threshold: 0.3
Metadata: {'model_type': 'XGBoost', 'model_version': '1.0', 'validation_metrics': {'precision': 0.5325301204819277, 'recall': 0.7892857142857143, 'f1': 0.6359712230215827, 'roc_auc': 0.8468059646539028}, 'test_metrics': {'precision': 0.5501355013550135, 'recall': 0.7224199288256228, 'f1': 0.6246153846153846, 'roc_auc': 0.8312933374912865}}

In [156]:
from src.models.predict import predict_customer

customer = df.iloc[[0]].copy()

prediction_result = predict_customer(
    customer,
    loaded_artifact,
)

prediction_result

{'churn_probability': 0.6854717135429382, 'prediction': 1}

In [157]:
from src.models.train import train_model

print("train.py updated successfully.")

train.py updated successfully.

In [158]:
from src.data.splitting import split_data

print("splitting.py updated successfully.")

splitting.py updated successfully.

In [159]:
from src.training_pipeline import run_training_pipeline

print("training_pipeline.py updated successfully.")

training_pipeline.py updated successfully.

In [160]:
from src.training_pipeline import run_training_pipeline

result = run_training_pipeline()

result

{'artifact_path': WindowsPath('C:/Users/Ibtissam Bukhari/Desktop/Projects/customer-churn-mlops/models/churn_model.joblib'),
 'validation_metrics': {'precision': 0.5325301204819277,
  'recall': 0.7892857142857143,
  'f1': 0.6359712230215827,
  'roc_auc': 0.8468059646539028},
 'test_metrics': {'precision': 0.5501355013550135,
  'recall': 0.7224199288256228,
  'f1': 0.6246153846153846,
  'roc_auc': 0.8312933374912865}}

In [161]:
from src.config import (
    PROJECT_ROOT,
    RAW_DATA_PATH,
    ARTIFACT_PATH,
)

print("Project root:", PROJECT_ROOT)
print("Raw data:", RAW_DATA_PATH)
print("Artifact:", ARTIFACT_PATH)
print("Raw data exists:", RAW_DATA_PATH.exists())

Project root: C:\Users\Ibtissam Bukhari\Desktop\Projects\customer-churn-mlops
Raw data: C:\Users\Ibtissam Bukhari\Desktop\Projects\customer-churn-mlops\data\raw\Telco-Customer-Churn.csv
Artifact: C:\Users\Ibtissam Bukhari\Desktop\Projects\customer-churn-mlops\models\churn_model.joblib
Raw data exists: True

In [162]:
from src.data.splitting import split_data

print("splitting.py updated successfully.")

splitting.py updated successfully.

In [163]:
from src.features.preprocessing import prepare_features, prepare_target
from src.data.splitting import split_data

X = prepare_features(df)
y = prepare_target(df["Churn"])

X_train, X_val, X_test, y_train, y_val, y_test = split_data(X, y)

print("Total:", len(X))
print("Train:", len(X_train))
print("Validation:", len(X_val))
print("Test:", len(X_test))

print("\nProportions:")
print("Train:", len(X_train) / len(X))
print("Validation:", len(X_val) / len(X))
print("Test:", len(X_test) / len(X))

Total: 7043
Train: 4930
Validation: 1056
Test: 1057

Proportions:
Train: 0.6999858015050404
Validation: 0.1499361067726821
Test: 0.15007809172227743

In [164]:
from src.config import (
    MODEL_TYPE,
    MODEL_VERSION,
    TARGET_COLUMN,
)

print("Model type:", MODEL_TYPE)
print("Model version:", MODEL_VERSION)
print("Target column:", TARGET_COLUMN)

Model type: XGBoost
Model version: 1.0
Target column: Churn

In [165]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))
from src.config import (
    MODEL_TYPE,
    MODEL_VERSION,
    TARGET_COLUMN,
)

print("Model type:", MODEL_TYPE)
print("Model version:", MODEL_VERSION)
print("Target column:", TARGET_COLUMN)

Model type: XGBoost
Model version: 1.0
Target column: Churn

In [166]:
from src.features.preprocessing import prepare_features

print("preprocessing.py imported successfully.")

preprocessing.py imported successfully.

In [167]:
from src.training_pipeline import run_training_pipeline

print("training_pipeline.py imported successfully.")

training_pipeline.py imported successfully.

In [168]:
from src.training_pipeline import run_training_pipeline

result = run_training_pipeline()

result

{'artifact_path': WindowsPath('C:/Users/Ibtissam Bukhari/Desktop/Projects/customer-churn-mlops/models/churn_model.joblib'),
 'validation_metrics': {'precision': 0.5325301204819277,
  'recall': 0.7892857142857143,
  'f1': 0.6359712230215827,
  'roc_auc': 0.8468059646539028},
 'test_metrics': {'precision': 0.5501355013550135,
  'recall': 0.7224199288256228,
  'f1': 0.6246153846153846,
  'roc_auc': 0.8312933374912865}}

In [170]:
import mlflow

print(mlflow.get_tracking_uri())

sqlite:///C:/Users/Ibtissam%20Bukhari/Desktop/Projects/customer-churn-mlops/notebooks/mlflow.db

In [171]:
from pathlib import Path
import mlflow

PROJECT_ROOT = Path.cwd().parent
MLFLOW_DB_PATH = PROJECT_ROOT / "mlflow.db"

tracking_uri = f"sqlite:///{MLFLOW_DB_PATH}"

mlflow.set_tracking_uri(tracking_uri)

print("Tracking URI:", mlflow.get_tracking_uri())

Tracking URI: sqlite:///c:\Users\Ibtissam Bukhari\Desktop\Projects\customer-churn-mlops\mlflow.db

In [172]:
mlflow.set_experiment("customer-churn-mlops")

print("Experiment configured successfully.")

2026/10/06 15:11:27 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/10/06 15:11:28 INFO mlflow.store.db.utils: Updating database tables
2026/10/06 15:11:31 INFO mlflow.tracking.fluent: Experiment with name 'customer-churn-mlops' does not exist. Creating a new experiment.

Experiment configured successfully.

In [173]:
with mlflow.start_run():
    print("Mlflow run started ")

print("mlflow run finished")

Mlflow run started
mlflow run finished

In [174]:
experiment = mlflow.get_experiment_by_name("customer-churn-mlops")

print("Experiment ID:", experiment.experiment_id)
print("Experiment name:", experiment.name)

Experiment ID: 1
Experiment name: customer-churn-mlops

In [175]:
runs = mlflow.search_runs(
    experiment_names=["customer-churn-mlops"]
)

print(runs[["run_id", "status", "start_time", "end_time"]])

                             run_id    status  \
0  40141ececfd84beba4238456a40f9bc9  FINISHED

                        start_time                         end_time
0 2026-10-06 10:18:00.094000+00:00 2026-10-06 10:18:00.178000+00:00

In [176]:
runs = mlflow.search_runs(
    experiment_names=["customer-churn-mlops"]
)

print(runs[["run_id", "status", "start_time", "end_time"]])

                             run_id    status  \
0  40141ececfd84beba4238456a40f9bc9  FINISHED

                        start_time                         end_time
0 2026-10-06 10:18:00.094000+00:00 2026-10-06 10:18:00.178000+00:00

In [177]:
import mlflow

runs = mlflow.search_runs(
    experiment_names=["customer-churn-mlops"]
)

runs[["run_id", "status", "start_time", "end_time"]]

,run_id,status,start_time,end_time
0,40141ececfd84beba4238456a40f9bc9,FINISHED,2026-10-06 10:18:00.094000+00:00,2026-10-06 10:18:00.178000+00:00

In [180]:
import mlflow

from src.config import MLFLOW_DB_PATH

mlflow.set_tracking_uri(f"sqlite:///{MLFLOW_DB_PATH}")
mlflow.set_experiment("customer-churn-mlops")

runs = mlflow.search_runs(
    experiment_names=["customer-churn-mlops"]
)

runs[["run_id", "status", "start_time", "end_time"]]

,run_id,status,start_time,end_time
0,23732d57e21d482286c085c214690393,FINISHED,2026-10-06 11:16:52.400000+00:00,2026-10-06 11:16:52.799000+00:00
1,361ad2e574ce40908156c26ad12873c5,FINISHED,2026-10-06 11:14:39.837000+00:00,2026-10-06 11:14:39.920000+00:00
2,40141ececfd84beba4238456a40f9bc9,FINISHED,2026-10-06 10:18:00.094000+00:00,2026-10-06 10:18:00.178000+00:00

In [179]:
import importlib
import src.config

importlib.reload(src.config)

print(src.config.MLFLOW_DB_PATH)

C:\Users\Ibtissam Bukhari\Desktop\Projects\customer-churn-mlops\mlflow.db

In [181]:
runs = mlflow.search_runs(
    experiment_names=["customer-churn-mlops"]
)

runs[[
    "run_id",
    "status",
    "params.n_estimators",
    "params.learning_rate",
    "params.max_depth",
    "params.random_state",
    "params.eval_metric",
]]

,run_id,status,params.n_estimators,params.learning_rate,params.max_depth,params.random_state,params.eval_metric
0,2919908841544ecd95639509152ffe56,FINISHED,200,0.05,4,42,logloss
1,23732d57e21d482286c085c214690393,FINISHED,NaN,NaN,NaN,NaN,NaN
2,361ad2e574ce40908156c26ad12873c5,FINISHED,NaN,NaN,NaN,NaN,NaN
3,40141ececfd84beba4238456a40f9bc9,FINISHED,NaN,NaN,NaN,NaN,NaN

In [186]:
runs = mlflow.search_runs(
    experiment_names=["customer-churn-mlops"]
)

runs[[
    "run_id",
    "status",
    # "metrics.validation_accuracy",
    "metrics.validation_precision",
    "metrics.validation_recall",
    "metrics.validation_f1",
    "metrics.validation_roc_auc",
    # "metrics.test_accuracy",
    "metrics.test_precision",
    "metrics.test_recall",
    "metrics.test_f1",
    "metrics.test_roc_auc",
]]

,run_id,status,metrics.validation_precision,metrics.validation_recall,metrics.validation_f1,metrics.validation_roc_auc,metrics.test_precision,metrics.test_recall,metrics.test_f1,metrics.test_roc_auc
0,f7753af4d3e34c51b9503dfb38e9f2a1,FINISHED,0.53253,0.789286,0.635971,0.846806,0.550136,0.72242,0.624615,0.831293
1,2919908841544ecd95639509152ffe56,FINISHED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,23732d57e21d482286c085c214690393,FINISHED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,361ad2e574ce40908156c26ad12873c5,FINISHED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,40141ececfd84beba4238456a40f9bc9,FINISHED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [184]:
runs = mlflow.search_runs(
    experiment_names=["customer-churn-mlops"]
)

print(runs.columns.tolist())

['run_id', 'experiment_id', 'status', 'artifact_uri', 'start_time', 'end_time', 'metrics.test_roc_auc', 'metrics.test_precision', 'metrics.validation_f1', 'metrics.test_recall', 'metrics.validation_recall', 'metrics.test_f1', 'metrics.validation_roc_auc', 'metrics.validation_precision', 'params.random_state', 'params.max_depth', 'params.n_estimators', 'params.learning_rate', 'params.eval_metric', 'tags.mlflow.user', 'tags.mlflow.source.type', 'tags.mlflow.source.git.branch', 'tags.mlflow.source.git.commit', 'tags.mlflow.source.name', 'tags.mlflow.runName']

In [185]:
runs.iloc[0][[
    "run_id",
    "metrics.validation_f1",
    "metrics.validation_precision",
    "metrics.validation_recall",
    "metrics.validation_roc_auc",
    "metrics.test_f1",
    "metrics.test_precision",
    "metrics.test_recall",
    "metrics.test_roc_auc",
]]

run_id                          f7753af4d3e34c51b9503dfb38e9f2a1
metrics.validation_f1                                   0.635971
metrics.validation_precision                             0.53253
metrics.validation_recall                               0.789286
metrics.validation_roc_auc                              0.846806
metrics.test_f1                                         0.624615
metrics.test_precision                                  0.550136
metrics.test_recall                                      0.72242
metrics.test_roc_auc                                    0.831293
Name: 0, dtype: object

In [187]:
runs = mlflow.search_runs(
    experiment_names=["customer-churn-mlops"]
)

latest_run_id = runs.iloc[0]["run_id"]

print("Latest run:", latest_run_id)

Latest run: d02eb334c7674ae586072a4c4401f5b9

In [188]:
artifacts = mlflow.artifacts.list_artifacts(run_id=latest_run_id)

for artifact in artifacts:
    print(artifact.path)

churn_model.joblib

In [189]:
runs = mlflow.search_runs(
    experiment_names=["customer-churn-mlops"]
)

latest_run = runs.iloc[0]

print("Run ID:", latest_run["run_id"])
print("Decision threshold:", latest_run["params.decision_threshold"])

Run ID: 50eeb185bfd8489baf24aea823857bfb
Decision threshold: 0.3

In [190]:
from src.models.evaluate import calculate_metrics

print(calculate_metrics(
    y_val.to_numpy(),
    val_predictions,
    val_probabilities
))

NameError: name 'val_predictions' is not defined

In [191]:
import numpy as np

y_true = np.array([0, 1, 1, 0, 1])
y_pred = np.array([0, 1, 0, 0, 1])
probabilities = np.array([0.10, 0.80, 0.40, 0.20, 0.90])

metrics = calculate_metrics(
    y_true,
    y_pred,
    probabilities
)

print(metrics)

{'precision': 1.0, 'recall': 0.6666666666666666, 'f1': 0.8, 'roc_auc': 1.0}

In [192]:
metrics = calculate_metrics(
    y_true,
    y_pred,
    probabilities
)

print(metrics)

{'precision': 1.0, 'recall': 0.6666666666666666, 'f1': 0.8, 'roc_auc': 1.0}

In [193]:
import importlib
import src.models.evaluate

importlib.reload(src.models.evaluate)

calculate_metrics = src.models.evaluate.calculate_metrics

In [194]:
metrics = calculate_metrics(
    y_true,
    y_pred,
    probabilities
)

print(metrics)

{'accuracy': 0.8, 'precision': 1.0, 'recall': 0.6666666666666666, 'f1': 0.8, 'roc_auc': 1.0}

In [195]:
runs = mlflow.search_runs(
    experiment_names=["customer-churn-mlops"]
)

latest_run = runs.iloc[0]

print("Run ID:", latest_run["run_id"])
print("\nMetrics:")
print(latest_run.filter(like="metrics."))

Run ID: 3bdc75bb283f4172ae59a7170b346a7a

Metrics:
metrics.test_roc_auc            0.831293
metrics.validation_accuracy     0.760417
metrics.test_accuracy           0.769158
metrics.test_precision          0.550136
metrics.validation_f1           0.635971
metrics.test_recall              0.72242
metrics.validation_recall       0.789286
metrics.test_f1                 0.624615
metrics.validation_roc_auc      0.846806
metrics.validation_precision     0.53253
Name: 0, dtype: object

In [196]:
print("Tracking URI:")
print(mlflow.get_tracking_uri())

experiment = mlflow.get_experiment_by_name("customer-churn-mlops")

print("\nExperiment artifact location:")
print(experiment.artifact_location)

Tracking URI:
sqlite:///C:\Users\Ibtissam Bukhari\Desktop\Projects\customer-churn-mlops\mlflow.db

Experiment artifact location:
file:///c:/Users/Ibtissam Bukhari/Desktop/Projects/customer-churn-mlops/notebooks/mlruns/1

In [197]:
from pathlib import Path
import mlflow

PROJECT_ROOT = Path.cwd().parent
MLRUNS_PATH = PROJECT_ROOT / "mlruns"

artifact_location = MLRUNS_PATH.as_uri()

new_experiment_name = "customer-churn-mlops-v2"

experiment_id = mlflow.create_experiment(
    new_experiment_name,
    artifact_location=artifact_location,
)

print("Experiment ID:", experiment_id)
print("Artifact location:", artifact_location)

Experiment ID: 2
Artifact location: file:///c:/Users/Ibtissam%20Bukhari/Desktop/Projects/customer-churn-mlops/mlruns

In [198]:
experiment = mlflow.get_experiment_by_name("customer-churn-mlops-v2")

print("Experiment ID:", experiment.experiment_id)
print("Artifact location:", experiment.artifact_location)

runs = mlflow.search_runs(
    experiment_names=["customer-churn-mlops-v2"]
)

print("\nNumber of runs:", len(runs))
print("\nLatest run ID:", runs.iloc[0]["run_id"])

Experiment ID: 2
Artifact location: file:///c:/Users/Ibtissam%20Bukhari/Desktop/Projects/customer-churn-mlops/mlruns

Number of runs: 1

Latest run ID: 94b0ca4cc1514fefa34d1788aeb2b18a

In [199]:
latest_run_id = runs.iloc[0]["run_id"]

artifacts = mlflow.artifacts.list_artifacts(
    run_id=latest_run_id
)

print("\nArtifacts:")
for artifact in artifacts:
    print(artifact.path)

Artifacts:
churn_model.joblib